name: Build ARM

on: [push, pull_request]

jobs:
  build_macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: altmannmarcelo/rust-compile-image:latest
          options: -v "${{ github.workspace }}":/usr/src/myapp -w /usr/src/myapp
          run: |
              cargo build --release
              cargo generate-rpm
              cargo deb
    - name: Save RPM / DEB name
      run: |
        echo "rpm_name=$(ls target/generate-rpm/)" >> "$GITHUB_ENV"
        echo "deb_name=$(ls target/debian/ -I *-stripped)" >> "$GITHUB_ENV"

    - name: Upload RPM
      uses: actions/upload-artifact@v4
      with:
        path: target/generate-rpm/
        name: ${{ env.rpm_name }}

    - name: Upload Deb
      uses: actions/upload-artifact@v4
      with:
        path: target/debian/${{ env.deb_name }}
        name: ${{ env.deb_name }}
